pipeline {
    agent {
        any {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                bat('mvn -B -DskipTests clean package')
            }
        }
    
        stage('SonarQube Analysis') {
            steps {
                  sh "mvn clean verify sonar:sonar"
                  }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
