pipeline {
        agent any
        tools {
        // Use the correct SonarQube installation name
        SonarQube 'SonarQubeScanner'
    }
        stages {
         
          stage("build & SonarQube Scanner") {
            agent any
            steps {
              withSonarQubeEnv('SonarQubeScanner') {
                sh 'mvn clean package sonar:sonar'
              }
            }
          }
        }
      }
